{
  "apiVersion": 1,
  "datasources": [
    {
      "name": "Prometheus",
      "type": "prometheus",
      "access": "proxy",
      "url": "http://prometheus:9090",
      "isDefault": true,
      "editable": true,
      "jsonData": {
        "timeInterval": "15s"
      }
    },
    {
      "name": "PostgreSQL",
      "type": "postgres",
      "access": "proxy",
      "url": "postgres:5432",
      "database": "policy0",
      "user": "policy0",
      "editable": true,
      "jsonData": {
        "sslmode": "disable",
        "maxOpenConns": 100,
        "maxIdleConns": 100,
        "maxIdleConnsAuto": true,
        "connMaxLifetime": 14400,
        "postgresVersion": 160000,
        "timescaledb": false
      },
      "secureJsonData": {
        "password": "${POSTGRES_PASSWORD}"
      }
    }
  ]
}